### PR TITLE
fix: add cjs file

### PR DESCRIPTION
**Pull request by GrassHopper42**
## Issue

#72

### CODE REVIEW

**Review by daybrush — CHANGES_REQUESTED** [review]
very nice.

You seem to be using m1 or MAC 12.

Uninstall codeceptjs-resemblehelper and install playwright@latest.
Restore the rest of the modules to their original state.

I am using playwright for e2e testing.

**Comment by daybrush** [comment]
```diff
- "codeceptjs-resemblehelper": "^1.9.3",
- "playwright": "^1.10.0",
+ "playwright": "^1.25.1",
```

**Comment by daybrush** [comment]
@GrassHopper42 

Except for resemble, restore codeceptjs related modules to their original state.

**Review by daybrush — APPROVED** [review]
LGTM

**Comment by GrassHopper42** [comment]
This version seems to be not published on npm, so I will do it on mine until you do.
If you publish, I will delete it.

**Review by malangfox — APPROVED** [review]
LGTM

**Review by WoodNeck — APPROVED** [review]
LGTM

**Pull request merged**
