### PR TITLE
fix: support svelte ssr

### PR DESCRIPTION
**Pull request by daybrush**
## Issue

#45

### CODE REVIEW

**Review by mixed — APPROVED** [review]
LGTM

**Review by WoodNeck — APPROVED** [review]
LGTM, looks like all components are imported as object instead of class/function in SSR or cjs env?
I guess Flicking & View360 update is also needed.

**Review by malangfox — APPROVED** [review]
LGTM

**Comment by daybrush** [comment]
@WoodNeck 

In ssr, it is an object.

**Pull request merged**
