### PR TITLE
feat: add isSizeCrop, displayedRow, offset in JustifiedGrid

### PR DESCRIPTION
**Pull request by daybrush**
## Issue

offset
#13 

isSizeCrop
#14 

displayedRow
#15

### CODE REVIEW

**Review by WoodNeck — APPROVED** [review]
LGTM,
I think the `isSizeCrop` should be renamed like `cropSize` or `isSizeCropped` or something though.

**Review by mixed — APPROVED** [review]
LGTM

**Comment by daybrush** [comment]
@WoodNeck 

How about `isCroppedSize`?

**Comment by WoodNeck** [comment]
If you think the option means the user provides a cropped size, that would be fine.
But if it means that the component should crop a given image/element's size, I think it's better to use `cropSize`

**Pull request merged**
